name: CI Tests

on:
  push:  # Run on every push to any branch
  pull_request:
    branches: [ main, master ]

jobs:
  # Main test job that must pass
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Run all tests
      run: npm test
      env:
        NODE_ENV: test
        CI: true

    - name: Build project
      run: npm run build
      
    - name: ✅ All checks passed
      run: echo "✅ All tests passed! Code is ready."
